config/routes.rb
  Rails.application.routes.draw do


  get 'projects/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'refugees/new'

  root 'static_pages#home'

  get '/help',         to: 'static_pages#help'
  get  '/about',       to: 'static_pages#about'
  get '/contact',      to: 'static_pages#contact'
  get '/signup',       to: 'users#new'
  post '/signup',      to: 'users#create'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  get  '/addRefugee',  to: 'refugees#new'
  post '/addRefugee',  to: 'refugees#create'
  get '/form',         to: 'static_pages#form'
  get '/newproject',   to: 'projects#new'

  resources :users
  resources :refugees
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :projects,            only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!--
<footer id="footer">
  <small>
    &copy; Profugees
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

-->
<!-- ------------------ -->

<!--<div id="footer">-->
<footer class="footer">
  <div class="container text-center">
    <div class="col-md-4">
      <h3></h3>
      <div class="contact-item">
        <p></p>
        <p></p>
      </div>
    </div>
    <div class="col-md-4">
      <h3></h3>
      <div class="contact-item">
        <p></p>
        <p></p>
      </div>
    </div>
    <div class="col-md-4">
      <h3></h3>
      <div class="contact-item">
        <p></p>
        <p></p>
      </div>
    </div>
  </div>
  <div class="container-fluid text-center copyrights">
    <div class="col-md-8 col-md-offset-2">
      <div class="social">
        <ul>
          <li><a href="https://www.facebook.com/Profugees-387829534925909/" target="_blank"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#" target="_blank"><i class="fa fa-instagram"></i></a></li>
          <li><a href="#" target="_blank"><i class="fa fa-youtube"></i></a></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "ContactUs", contact_path %><li>
        </ul>
      </div>
      <p>&copy; 2017 Profugees. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--
<nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
          data-target="#navbar-collapse">
        <span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
    <%= link_to "Profugees", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Refugees", refugees_path %></li>
        <li><%= link_to "FAQ", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", login_path, class: "btn btn-primary navbar-btn navbar-right" %>
          <%= link_to "Sign up", signup_path, class: "btn btn-primary navbar-btn navbar-right" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

-->

<!-- --------------- -->


<nav id="menu" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
      data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a href=/ class=""><img
            src="http://i.imgur.com/ygtKoTC.png"
            height="75" width="75"></a>
            <!-- OUR LOGO 2 LINES UP-->
      <%= link_to "", root_path, class: "navbar-brand page-scroll" %></div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" id="nav-bar">
      	<li><%= link_to "Home", root_path, class: "page-scroll" %></li>
        <% if logged_in? && admin? %>
        <li><%= link_to "AddRefugees", addRefugee_path, class: "page-scroll" %></li>
        <% end %>
        <li><%= link_to "Refugees", refugees_path, class: "page-scroll" %></li>
        <li><%= link_to "Projects", projects_path, class: "page-scroll" %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <!-- Meh -->
    <!--
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
                  crossorigin="anonymous">
    -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link rel="stylesheet" type="text/css"  href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="fonts/font-awesome/css/font-awesome.css">

    <!-- Stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700" rel="stylesheet">

    <!-- Meh -->

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>


    <!-- summernote -->
    <!--
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css" rel="stylesheet">
    -->

    <!-- Tinymce -->
    <!-- <script src="//cloud.tinymce.com/stable/tinymce.min.js"></script> -->

  </head>

  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>